[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci", "cd plugins/capacitor-mapbox-maps && npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node scripts/serve-dist.mjs"
